---
title: "FP 653 Project Script"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#load librarys 
library(tidyverse)
library(janitor)
library(ggplot2)
library(here)
library(rio)
library(usmap)
library(maps)
library(glue)
library(sp)
library(shiny)
library(reactable)
library(formattable)
#library(bslib)
library(shinythemes)
library(RSocrata)
library(covidcast)
library(sf)

```

```{r}
#functions for later
#function1, save plots to a folder 


#function2, convert month numbers into indicative string 

#numbers to month names, not done yet
#numbers to month function, generalized(not really, works for columns consisitng of numeric 1-12) doesnt work on grouped data, feed to mutate  
monthnum_to_names <- function(data, column) {

  check <- with(data, column >= 1 & column <= 12)
  if (unique(check) == "False") {
    return(NA) }
  else {
    return(month.name[column])
  } 
}
monthnum_to_names(table_attendance, table_attendance$month)


```


```{r}
#Chris merges this later on so will delete once I can get his portion organized
  #bring in data
  
  county_sch <- import(here("schools_county_csv2.xlsx")) %>% 
    clean_names() %>%
    as_tibble()
  
  #need the variable 'fips' for mapping
  cmap <- rename(county_sch, "fips" = "countyfips4")
  
  #only keep 2020 data
  cmap2020 <- 
    cmap %>% 
    filter(year == 2020) %>% 
    group_by(month)
  
  
  #check min max of share_all_closed_50 for scaling reasons
  min(cmap2020$share_all_closed_50, na.rm = T)
  max(cmap2020$share_all_closed_50, na.rm = T)
  mean(cmap2020$share_all_closed_50, na.rm = T)
  sd(cmap2020$share_all_closed_50, na.rm = T)
  


```

```{r}
#functions for later
#function1, save plots to a folder 


#function2, convert month numbers into indicative string 

#numbers to month function, generalized(not really, works for columns consisitng of numeric 1-12) doesnt work on grouped data, feed to mutate  
monthnum_to_names <- function(data, column) {

  check <- with(data, column >= 1 & column <= 12)
  if (unique(check) == "False") {
    return(NA) }
  else {
    return(month.name[column])
  } 
}

```


```{r}
#Consolidated dataframe to use as base
#Count Cases by County and Age Group
# Import COVID Case data for 2020 in West Coast States(CA, OR, WA)
covid_data <- import("west_coast_covid_data.csv") 
  

# Cleaning covid_data
county_covid <- covid_data %>%
  drop_na(county_fips_code) %>% 
  group_by(case_month, county_fips_code, age_group) %>% 
  nest() %>% 
  mutate(total_cases = map_dbl(data, ~nrow(.x)),
         age_group = ifelse(is.na(age_group), "Unknown", age_group),
         case_month = as.numeric(
           substr(case_month, 6, 7))) %>% 
  select(-data) %>% 
  arrange(county_fips_code, case_month)


## Importing population data for per capita estimates
county_demo <- covidcast::county_census %>% 
  janitor::clean_names() %>% 
  select(fips, popestimate2019)


## Joining population data with covid case data and calculating additional variables
covid_cases <- county_covid %>% 
  rename(fips = county_fips_code,
         month = case_month) %>% ##moving his earlier in the pipe
  mutate(fips = str_pad(fips, width = 5, side = "left", pad = "0")) %>% 
  group_by(fips, month) %>% 
  mutate(all_cases = sum(total_cases)) %>% 
  ungroup() %>% 
  mutate(month_names = monthnum_to_names(county_covid, county_covid$case_month)) %>% 
  left_join(county_demo) %>% 
  distinct(month, month_names, fips, all_cases, popestimate2019) %>% 
  group_by(fips, month) %>% 
  mutate(capita_covid = round((all_cases/(popestimate2019/100000)), 2),
         per_pop = round((1/(all_cases/popestimate2019)), 0),
         share_pop = paste("1 in", per_pop, sep = " ")) %>% 
         # fips = as.integer(fips)) %>% #changed fips type here to integer for later use
  select(fips, month, month_names,capita_covid, all_cases, per_pop, share_pop)

export(covid_cases, "county_case_counts.csv")

## Process Attendance Data
county_data <- read.csv("schools_county_csv.csv") %>% 
  filter(year == 2020) %>% 
  rename(fips = countyfips3) %>% 
  mutate(fips = as.character(fips),
         fips = str_pad(fips, width = 5, side = "left", pad = "0"),
         across(7:18, ~ .x *100),
         month_names = monthnum_to_names(., .$month))

export(county_data, "app_attendance_data.csv")

app_data <- county_data %>% 
  left_join(covid_cases)

export(app_data, "app_data.csv")

# Import Mapping data
wst_cst <- tigris::counties(state = c("California", "Oregon", "Washington")) %>% 
  janitor::clean_names() %>% 
  select(geoid, geometry) %>% 
  rename(fips = geoid)

write_sf(wst_cst, "wst_cst.shp")

```

```{r}

#Chris' mapping stuff
## Import Map Data
map_url <- 'https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json'

#Join different data sources
covid_data <- county_data %>% 
    left_join(covid_cases, by = c("fips", "month"))



counties_json <- rjson::fromJSON(file = url) %>% 
  unnest()

export(covid_data, "app_data.csv")


wst_cst <- tigris::counties(state = c("California", "Oregon", "Washington")) %>% 
  janitor::clean_names() %>% 
  select(geoid, geometry) %>% 
  rename(fips = geoid)

us_map <- tigris::counties() %>% 
  janitor::clean_names()

us_map <- us_map %>% 
  janitor::clean_names() %>% 
  select(geoid, geometry) %>% 
  rename(fips = geoid)


write_sf(us_map, "us_county_geom.shp")
write_sf(wst_cst, "wst_cst.shp")

```


```{r}
#Racheals cdc plots
cdc_plots <- county_covid %>% #need to reference county_covid, watch out for some column names for the time being 
  group_by( fips) %>% 
  nest() %>% 
  mutate(plot = pmap(list(fips, data), ~{
    ggplot(..2, aes(x=case_month,
                    y=total_cases,
                    color = age_group)) +
      geom_point() +
      geom_line(alpha = 0.7, size = 1) +
      scale_x_discrete(limits = c(0, max(cdc$case_month)), 
                       expand = c(0, 0)) +
      labs(title = glue("County with FIPS code: {.x} "),
           x = "Month in 2020",
           y = "Total Cases",
           color = 'Age Group')
  })
  )
#example plot
cdc_plots$plot[[1]]  

fs::dir_create(here::here("plots"))
county <- str_replace_all(tolower(cdc_plots$fips), " ", "-")
path <- here::here("plots", glue("{county}.png"))

walk2(path, cdc_plots$plot, ggsave,
      width = 9.5, 
      height = 6.5,
      dpi = 500)


```


```{r}
#table of CDC data
cmap2020_2 <- county_data %>% 
  mutate(fips = as.integer(fips))

cdc_table_data<-left_join(covid_cases,cmap2020_2) %>% #using covid_cases for cdc 
  select(1, 8, 25, 26, 3, 4)

cdc_table <- cdc_table_data %>% 
  reactable(
  searchable = TRUE,
  filterable = TRUE,
  columns = list(
    case_month = colDef(name="Month"),
    year = colDef(name="Year"),
    county_name = colDef(name="County"),
    state_abb = colDef(name="State"),
    age_group = colDef(name="Age group"),
    total_cases = colDef(name="Total COVID-19 cases")),
  defaultPageSize = 11
  )

cdc_table

```



```{r}
#saving plots to file


```

```{r}
#table for attendance data, with reactable? meant for shiny app will move it to the app once I know whats going on

table_attendance <- cmap2020 %>% #change data to master dataframe
  ungroup() %>%
  mutate(month = monthnum_to_names(cmap2020, cmap2020$month)) %>% #also remove later since ill do this when organizing data
  filter(state_abb == "OR") %>% #remove this once consolidated dataframe is done
  select(month, county_name, total_students, number_schools, share_all_closed_25, share_all_closed_50, share_all_closed_75, mean_all_change, fips) %>% #watch out for what fips is called later on
  rename("Ratio of Schools with at least 25% vistor decline from 2019" = share_all_closed_25,
         "Ratio of Schools with at least 50% vistor decline from 2019" = share_all_closed_50,
         "Ratio of Schools with at least 75% vistor decline from 2019" = share_all_closed_75,
         "Mean change ratio of in person visits from 2019 (+:Decline from 2019,-:Increase from 2019)" = mean_all_change,
         "Month" = month,
         "County Name" = county_name,
         "Total Students" = total_students,
         "Number of Schools" = number_schools)



#shiny app stuff for table
ui <- fluidPage(
  reactableOutput("table"), theme = shinytheme("cyborg")
)

server <- function(input, output) {
  output$table <- renderReactable({
    reactable(table_attendance,
              filterable = TRUE,
              defaultPageSize = 25,
    )
    
  })
}

shinyApp(ui, server)

ggplot()





```